--db2 CREATE DATABASE NRDATA ON C: USING CODESET IBM-1252 TERRITORY US COLLATE USING SYSTEM

--CONNECT TO NRDATA USER Zilin USING Admin123;


--DROP TABLE "PUBLIC "."COMMUNITY_ADDR";
--DROP TABLE "PUBLIC "."COMMUNITY_BRCH";
--DROP TABLE "PUBLIC "."COMMUNITY_TYPE_ACCT";
--DROP TABLE "PUBLIC "."CRM_ACCT_TYPE";
--DROP TABLE "PUBLIC "."CRM_ADDRESS" ;
--DROP TABLE "PUBLIC "."CRM_CRMBRCH" ;
--DROP TABLE "PUBLIC "."HR_ACCT_NAMES" ;
--DROP TABLE "PUBLIC "."HR_ADDR_TYPE";
--DROP TABLE "PUBLIC "."HR_BRCHS";

CREATE TABLE "PUBLIC "."COMMUNITY_ADDR"  (
		  "ADDRESS_TYPE_CODE" VARCHAR(5) NOT NULL , 
		  "ADDRESS_TYPE_DESC" VARCHAR(50),  
		  "CREATE_DATE" TIMESTAMP , 
		  "CREATOR" VARCHAR(50) , 
		  "LAST_UPDATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(50))
		 IN "USERSPACE1" ; 
 

CREATE TABLE "PUBLIC "."COMMUNITY_BRCH"  (
		  "SEQ" INTEGER , 
		  "ACCT_ID" VARCHAR(41) , 
		  "F_NAME" VARCHAR(30) , 
		  "M_NAME" VARCHAR(30) , 
		  "L_NAME" VARCHAR(30) , 
		  "SOCIAL" VARCHAR(15) , 
		  "GENDER" CHAR(1) , 
		  "BIRTHDAY" TIMESTAMP , 
		  "ADDRESS_LINE_1" VARCHAR(100) , 
		  "CITY" VARCHAR(20) , 
		  "STATE_PROV" VARCHAR(12) , 
		  "COUNTRY_NAME" VARCHAR(20) , 
		  "POSTAL_CD" VARCHAR(10) , 
		  "PRIMARY_PH" VARCHAR(30) , 
		  "CREDITCARD" VARCHAR(30) ,
		  "E_MAIL" VARCHAR(30) ,
		  "OVERDRAFT_IND" INTEGER , 
		  "CHRTY_DCNT" INTEGER , 
		  "KEY_2" VARCHAR(20) , 
		  "NOTE_1" VARCHAR(14) , 
		  "NOTE_2" VARCHAR(14) , 
		  "NOTE_3" VARCHAR(100) , 
		  "UPD_DT" TIMESTAMP )   
		 IN "USERSPACE1" ; 


CREATE TABLE "PUBLIC "."COMMUNITY_TYPE_ACCT"  (
		  "ACCOUNT_CODE" VARCHAR(5) NOT NULL , 
		  "ACCOUNT_NAME" VARCHAR(50), 
		  "CREATE_DATE" TIMESTAMP , 
		  "CREATOR" VARCHAR(50) , 
		  "LAST_UPDATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(50))
		 IN "USERSPACE1" ; 




CREATE TABLE "PUBLIC "."CRM_ACCT_TYPE"  (
		  "ACCOUNT_CODE" VARCHAR(5) NOT NULL , 
		  "ACCOUNT_NAME" VARCHAR(50),
		  "LAST_UPDATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(50) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "CREATOR" VARCHAR(50) )   
		 IN "USERSPACE1" ; 



CREATE TABLE "PUBLIC "."CRM_ADDRESS"  (
		  "ADDRESS_CODE" VARCHAR(5) NOT NULL , 
		  "ADDRESS_DESC" VARCHAR(50) ,
		  "LAST_UPDATE_DATE" TIMESTAMP , 
		  "UPDATED_BY" VARCHAR(50) , 
		  "CREATE_DATE" TIMESTAMP , 
		  "CREATOR" VARCHAR(50) ) 
		 IN "USERSPACE1" ; 



CREATE TABLE "PUBLIC "."CRM_BRCH"  (
		  "SEQ" INTEGER , 
		  "ID" VARCHAR(41) , 
		  "FIRST_NAME" VARCHAR(30) , 
		  "MIDDLE_NAME" VARCHAR(30) , 
		  "LAST_NAME" VARCHAR(30) , 
		  "CONTACT_NUM" VARCHAR(30) , 
		  "TAX_ID" VARCHAR(15) , 
		  "GENDER" CHAR(1) , 
		  "CCARD" VARCHAR(30) ,
		  "EMAIL" VARCHAR(30) ,
		  "INCOME_RANK" DECIMAL(10,0) , 
		  "BIRTH_DATE" TIMESTAMP , 
		  "ACCT_TYPE" VARCHAR(4) , 
		  "ADDRESS_TYPE" VARCHAR(4), 
		  "ADDRESS_LINE_1" VARCHAR(100) , 
		  "CITY" VARCHAR(20) , 
		  "STATE" VARCHAR(12) , 
		  "COUNTRY" VARCHAR(20) , 
		  "POSTAL_CODE" VARCHAR(10) , 
		  "HP_REF_1" VARCHAR(3) , 
		  "SBX_IND" INTEGER , 
		  "EXF_DT" TIMESTAMP , 
		  "UPD_REG_DT" TIMESTAMP )   
		 IN "USERSPACE1" ; 



CREATE TABLE "PUBLIC "."HR_ACCT_NAMES"  (
		  "ACCOUNT_CODE" VARCHAR(7) , 
		  "ACCOUNT_NAME" VARCHAR(50),			  
		  "CREATOR" VARCHAR(50),
		"CREATE_DATE" TIMESTAMP , 
		"UPDATED_BY" VARCHAR(50) )   
		 IN "USERSPACE1" ; 

 

CREATE TABLE "PUBLIC "."HR_ADDR_TYPE"  (		   
		  "ADDRESS_TYPE_CODE" VARCHAR(5) NOT NULL , 
		  "ADDRESS_TYPE_DESC" VARCHAR(50),
		"CREATOR" VARCHAR(50) , 
		"CREATE_DATE" TIMESTAMP ,
		"UPDATED_BY" VARCHAR(50) , 
		"LAST_UPDATE_DATE" TIMESTAMP  )   
		 IN "USERSPACE1" ; 



CREATE TABLE "PUBLIC "."HR_BRCHS"  (
		  "SEQ" INTEGER , 
		  "CUST_ID" VARCHAR(41) , 
		  "FN" VARCHAR(30) , 
		  "MI" VARCHAR(30) , 
		  "LN" VARCHAR(30) , 
		  "SSN" VARCHAR(9) , 
		  "SEX" CHAR(1) , 
		  "HC_CODE" INTEGER , 
		  "DOB" TIMESTAMP , 
		  "ACCT_KIND" VARCHAR(4) , 
		  "ADDR_KIND" VARCHAR(4) , 
		  "STREET_ADDR" VARCHAR(100) , 
		  "CITY" VARCHAR(20) , 
		  "STATE" VARCHAR(12) , 
		  "COUNTRY" VARCHAR(20) , 
		  "ZIP_CODE" VARCHAR(10) , 
		  "PERM_PH" VARCHAR(14) , 
		  "CARD" VARCHAR(30) ,
		  "EM" VARCHAR(30) ,
		  "REF_NO1" INTEGER , 
		  "REF_NO2" INTEGER , 
		  "DR_LB" INTEGER , 
		  "INS_REF" VARCHAR(10) , 
		  "TRST_IND" INTEGER , 
		  "DISCT_CD" INTEGER , 
		  "LAST_U_DT" TIMESTAMP )   
		 IN "USERSPACE1" ; 



--COMMIT WORK;

--CONNECT RESET;

--TERMINATE;