version: '3.4'

services:

  rabbitmq:
    image: rabbitmq:3.6.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
    # ports:
    #   - "15672"
    #   - "5672"
    healthcheck:
      test: ["CMD", "wget", "http://localhost:15672"]
      interval: 5s
      timeout: 5s
      retries: 10  
    logging:
      driver: "none"

  postgres:
    image: postgres:10.14
    environment:
      POSTGRES_PASSWORD: Admin123!
      POSTGRES_DB: nrdata
      POSTGRES_USER: postgres
    # ports:
    #   - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d nrdata"]
      interval: 3s
      timeout: 3s
      retries: 10
    logging:
      driver: "none"

  redis:
    image: redis:latest
    command: redis-server --requirepass Admin123
    #ports:
    #  - "6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
    #  - DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
    healthcheck:
      test: ["CMD-SHELL", "redis-cli", "ping"]
      interval: 2s
      timeout: 3s
      retries: 10
    logging:
      driver: "none"

